/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Reno
 */
import javax.swing.JOptionPane;
public class uii extends javax.swing.JFrame {

    /**
     * Creates new form uii
     */
    public uii() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCBSoto = new javax.swing.JCheckBox();
        jCBRawon = new javax.swing.JCheckBox();
        jCBBakso = new javax.swing.JCheckBox();
        jCBGudeg = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFBakso = new javax.swing.JTextField();
        jTFRawon = new javax.swing.JTextField();
        jTFGudeg = new javax.swing.JTextField();
        jTFSoto = new javax.swing.JTextField();
        jLSoto = new javax.swing.JLabel();
        jLBakso = new javax.swing.JLabel();
        jLRawon = new javax.swing.JLabel();
        jLTotalPorsi = new javax.swing.JLabel();
        jButtonKeluar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLTotalHarga = new javax.swing.JLabel();
        jLGudeg = new javax.swing.JLabel();
        jButtonHitung = new javax.swing.JButton();
        jButtonUlang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAK MAN FOODCOURT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SOTO || RAWON || BAKSO || GUDEG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        jCBSoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBSoto.setForeground(new java.awt.Color(0, 0, 0));
        jCBSoto.setText("SOTO");
        jCBSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSotoActionPerformed(evt);
            }
        });
        jCBSoto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCBSotoPropertyChange(evt);
            }
        });

        jCBRawon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBRawon.setForeground(new java.awt.Color(0, 0, 0));
        jCBRawon.setText("RAWON");
        jCBRawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBRawonActionPerformed(evt);
            }
        });
        jCBRawon.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCBRawonPropertyChange(evt);
            }
        });

        jCBBakso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBBakso.setForeground(new java.awt.Color(0, 0, 0));
        jCBBakso.setText("BAKSO");
        jCBBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBaksoActionPerformed(evt);
            }
        });
        jCBBakso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCBBaksoPropertyChange(evt);
            }
        });

        jCBGudeg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCBGudeg.setForeground(new java.awt.Color(0, 0, 0));
        jCBGudeg.setText("GUDEG");
        jCBGudeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGudegActionPerformed(evt);
            }
        });
        jCBGudeg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCBGudegPropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MAKANAN");

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("HARGA");

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("HARGA TOTAL");

        jLabel6.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("JUMLAH");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rp. 6000,-");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Rp. 4000,-");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Rp. 5000,-");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Rp. 5000,-");

        jTFBakso.setBackground(new java.awt.Color(255, 255, 255));

        jTFRawon.setBackground(new java.awt.Color(255, 255, 255));

        jTFGudeg.setBackground(new java.awt.Color(255, 255, 255));
        jTFGudeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFGudegActionPerformed(evt);
            }
        });
        jTFGudeg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTFGudegPropertyChange(evt);
            }
        });

        jTFSoto.setBackground(new java.awt.Color(255, 255, 255));

        jLSoto.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLSoto.setForeground(new java.awt.Color(0, 0, 0));
        jLSoto.setText("Rp.");

        jLBakso.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLBakso.setForeground(new java.awt.Color(0, 0, 0));
        jLBakso.setText("Rp.");

        jLRawon.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLRawon.setForeground(new java.awt.Color(0, 0, 0));
        jLRawon.setText("Rp.");

        jLTotalPorsi.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLTotalPorsi.setForeground(new java.awt.Color(0, 0, 0));
        jLTotalPorsi.setText("Porsi");

        jButtonKeluar.setBackground(new java.awt.Color(255, 102, 102));
        jButtonKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Total Bayar");

        jLTotalHarga.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLTotalHarga.setForeground(new java.awt.Color(0, 0, 0));
        jLTotalHarga.setText("Rp. ");

        jLGudeg.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLGudeg.setForeground(new java.awt.Color(0, 0, 0));
        jLGudeg.setText("Rp. ");

        jButtonHitung.setBackground(new java.awt.Color(0, 153, 0));
        jButtonHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonHitung.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHitung.setText("HITUNG");
        jButtonHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungActionPerformed(evt);
            }
        });

        jButtonUlang.setBackground(new java.awt.Color(0, 51, 204));
        jButtonUlang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUlang.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUlang.setText("ULANG");
        jButtonUlang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUlangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCBSoto)
                                .addComponent(jCBRawon)
                                .addComponent(jCBBakso)
                                .addComponent(jCBGudeg)))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUlang)
                        .addGap(53, 53, 53)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLTotalPorsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jTFSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFRawon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFGudeg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLSoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLRawon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jLGudeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKeluar)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBSoto)
                    .addComponent(jLabel9)
                    .addComponent(jTFSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSoto))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBRawon)
                    .addComponent(jLabel7)
                    .addComponent(jTFRawon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRawon))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBBakso)
                    .addComponent(jLabel8)
                    .addComponent(jTFBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBakso))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBGudeg)
                        .addComponent(jLabel10)
                        .addComponent(jTFGudeg, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLGudeg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLTotalPorsi)
                    .addComponent(jLTotalHarga))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static void pesan_kosong(String param){
        JOptionPane.showMessageDialog(null, "Jumlah Pesanan" + param  +"Belum Dimasukkan","Warning", JOptionPane.WARNING_MESSAGE);
    }
    private void jButtonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungActionPerformed
       int totalPorsi = 0;
       int totalHarga = 0;
        
        if (jCBSoto.isSelected()){
            if(jTFSoto.getText().isEmpty()){
                pesan_kosong(" SOTO ");
             }
            int jumlahPorsiSoto = Integer.parseInt(jTFSoto.getText());
            int hargaSoto = jumlahPorsiSoto*5000;
            totalPorsi += jumlahPorsiSoto;
            totalHarga += hargaSoto;
            jLSoto.setText("Rp. "+hargaSoto);
        }
        
        if (jCBRawon.isSelected()){
            if(jTFRawon.getText().isEmpty()){
                pesan_kosong(" RAWON ");
             }
            int jumlahPorsirRawon = Integer.parseInt(jTFRawon.getText());
            int hargaRawon = jumlahPorsirRawon*4000;
            totalPorsi += jumlahPorsirRawon;
            totalHarga += hargaRawon;
            jLRawon.setText("Rp. "+hargaRawon);
        }
        
        if (jCBGudeg.isSelected()){
            if(jTFGudeg.getText().isEmpty()){
                pesan_kosong(" GUDEG ");
             }
            int jumlahPorsiGudeg = Integer.parseInt(jTFGudeg.getText());
            int hargaGudeg = jumlahPorsiGudeg*4000;
            totalPorsi += jumlahPorsiGudeg;
            totalHarga += hargaGudeg;
            jLGudeg.setText("Rp. "+hargaGudeg);
        }
        
        if (jCBBakso.isSelected()){
            if(jTFBakso.getText().isEmpty()){
                pesan_kosong(" BAKSO ");
             }
            int jumlahPorsibakso = Integer.parseInt(jTFBakso.getText());
            int hargaBakso = jumlahPorsibakso*8000;
            totalPorsi += jumlahPorsibakso;
            totalHarga += hargaBakso;
            jLBakso.setText("Rp. "+hargaBakso);
            
        }
        
        jLTotalPorsi.setText( totalPorsi+" porsi" );
        jLTotalHarga.setText( "Rp. "+totalHarga );
    }//GEN-LAST:event_jButtonHitungActionPerformed

    private void jButtonUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUlangActionPerformed
//        RESET
        jLGudeg.setText("");
        jTFGudeg.setText("");
        jLBakso.setText("");
        jTFBakso.setText("");
        jLSoto.setText("");
        jTFSoto.setText("");
        jLRawon.setText("");
        jTFRawon.setText("");
        jLTotalPorsi.setText("");
        jLTotalHarga.setText("");
    }//GEN-LAST:event_jButtonUlangActionPerformed

    private void jCBSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSotoActionPerformed
      jTFSoto.setEnabled(false);
        if (jCBSoto.isSelected()){
           jTFSoto.setEnabled(true);
           jTFSoto.requestFocus();
        }
    }//GEN-LAST:event_jCBSotoActionPerformed

    private void jCBGudegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGudegActionPerformed
        jTFGudeg.setEnabled(false);
        if (jCBGudeg.isSelected()){
           jTFGudeg.setEnabled(true);
           jTFGudeg.requestFocus();
        }
    }//GEN-LAST:event_jCBGudegActionPerformed

    private void jCBRawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBRawonActionPerformed
       jTFRawon.setEnabled(false);
        if (jCBRawon.isSelected()){
           jTFRawon.setEnabled(true);
           jTFRawon.requestFocus();
        }
    }//GEN-LAST:event_jCBRawonActionPerformed

    private void jCBBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBaksoActionPerformed
        jTFBakso.setEnabled(false);
        if (jCBBakso.isSelected()){
           jTFBakso.setEnabled(true);
           jTFBakso.requestFocus();
        }
    }//GEN-LAST:event_jCBBaksoActionPerformed

    private void jCBSotoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCBSotoPropertyChange
          jTFSoto.setEnabled(false);
    }//GEN-LAST:event_jCBSotoPropertyChange

    private void jTFGudegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFGudegActionPerformed
        
    }//GEN-LAST:event_jTFGudegActionPerformed

    private void jTFGudegPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTFGudegPropertyChange

    }//GEN-LAST:event_jTFGudegPropertyChange

    private void jCBGudegPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCBGudegPropertyChange
        jTFGudeg.setEnabled(false);
    }//GEN-LAST:event_jCBGudegPropertyChange

    private void jCBRawonPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCBRawonPropertyChange
        jTFRawon.setEnabled(false);
    }//GEN-LAST:event_jCBRawonPropertyChange

    private void jCBBaksoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCBBaksoPropertyChange
        jTFBakso.setEnabled(false);
    }//GEN-LAST:event_jCBBaksoPropertyChange

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uii.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uii().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonUlang;
    private javax.swing.JCheckBox jCBBakso;
    private javax.swing.JCheckBox jCBGudeg;
    private javax.swing.JCheckBox jCBRawon;
    private javax.swing.JCheckBox jCBSoto;
    private javax.swing.JLabel jLBakso;
    private javax.swing.JLabel jLGudeg;
    private javax.swing.JLabel jLRawon;
    private javax.swing.JLabel jLSoto;
    private javax.swing.JLabel jLTotalHarga;
    private javax.swing.JLabel jLTotalPorsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFBakso;
    private javax.swing.JTextField jTFGudeg;
    private javax.swing.JTextField jTFRawon;
    private javax.swing.JTextField jTFSoto;
    // End of variables declaration//GEN-END:variables
}
